directory: /music

plugins: discogs lastgenre fetchart embedart lyrics fromfilename scrub

fetchart:
    cautious: yes
    minwidth: 500
    maxwidth: 500
    enforce_ratio: yes
    sources: itunes amazon coverart albumart filesystem
