library: /config/library.db
directory: /music

plugins: lastgenre fetchart embedart lyrics scrub

fetchart:
    cautious: yes
    minwidth: 500
    maxwidth: 500
    enforce_ratio: yes
    remote_priority: yes
    sources: amazon coverart itunes albumart
